version: '3.7'

services:

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile-stage
      cache_from:
        - $ECR_REPO/$USERS:$TRAVIS_BRANCH
    expose:
      - 5000
    environment:
      - FLASK_ENV=production
      - APP_SETTINGS=project.config.StagingConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_stage
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=my_precious
    depends_on:
      - users-db

  users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
      cache_from:
        - $ECR_REPO/$USERS_DB:$TRAVIS_BRANCH
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-stage
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile-stage
      cache_from:
        - $ECR_REPO/$CLIENT:$TRAVIS_BRANCH
      args:
        - NODE_ENV=production
        - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
        - REACT_APP_API_GATEWAY_URL=${REACT_APP_API_GATEWAY_URL}
        - REACT_APP_EXERCISES_SERVICE_URL=${REACT_APP_EXERCISES_SERVICE_URL}
    expose:
      - 80
    depends_on:
      - users

  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile-stage
      cache_from:
        - $ECR_REPO/$SWAGGER:$TRAVIS_BRANCH
    expose:
      - 8080
    environment:
      - URL=swagger.json
    depends_on:
      - users

  exercises:
    build:
      context: ./services/exercises
      dockerfile: Dockerfile-stage
    expose:
      - 5000
    environment:
      - APP_SETTINGS=project.config.StagingConfig
      - DATABASE_URL=postgres://postgres:postgres@exercises-db:5432/exercises_stage
      - DATABASE_TEST_URL=postgres://postgres:postgres@exercises-db:5432/exercises_test
      - FLASK_ENV=production
      # - USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - users
      - exercises-db

  exercises-db:
    build:
      context: ./services/exercises/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  scores:
    build:
      context: ./services/scores
      dockerfile: Dockerfile-stage
    volumes:
      - './services/scores:/usr/src/app'
    ports:
      - 5000
    environment:
      - APP_SETTINGS=project.config.StagingConfig
      - DATABASE_URL=postgres://postgres:postgres@scores-db:5432/scores_stage
      - DATABASE_TEST_URL=postgres://postgres:postgres@scores-db:5432/scores_test
      - EXERCISES_SERVICE_URL=${REACT_APP_EXERCISES_SERVICE_URL}
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=production
      - SECRET_KEY=my_precious
      - USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    depends_on:
      - users
      - exercises
      - scores-db

  scores-db:
    build:
      context: ./services/scores/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
