version: '3.7'

services:
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    volumes:
      - './services/users:/usr/src/app'
    expose:
      - 5000
    environment:
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
      - SECRET_KEY=my_precious
    depends_on:
      - users-db

  users-db:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  nginx:
    build:
      context: ./services/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    depends_on:
      - users
      - client

  client:
    build:
      context: ./services/client
      dockerfile: Dockerfile
    volumes:
      - './services/client:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_USERS_SERVICE_URL=http://localhost
      - REACT_APP_API_GATEWAY_URL=${REACT_APP_API_GATEWAY_URL}
      - REACT_APP_EXERCISES_SERVICE_URL=${REACT_APP_EXERCISES_SERVICE_URL}
      # - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
    stdin_open: true
    depends_on:
      - users

  swagger:
    build:
      context: ./services/swagger
      dockerfile: Dockerfile
    volumes:
      - './services/swagger/swagger.json:/usr/share/nginx/html/swagger.json'
    ports:
      - 3008:8080
    environment:
      - URL=swagger.json
    depends_on:
      - users

  exercises:
    build:
      context: ./services/exercises
      dockerfile: Dockerfile
    volumes:
      - './services/exercises:/usr/src/app'
    ports:
      - 5002:5000
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@exercises-db:5432/exercises_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@exercises-db:5432/exercises_test
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - SECRET_KEY=my_precious
      - USERS_SERVICE_URL=http://users:5000
    depends_on:
      - exercises-db
      - users

  exercises-db:
    build:
      context: ./services/exercises/project/db
      dockerfile: Dockerfile
    ports:
      - 5437:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  scores:
    build:
      context: ./services/scores
      dockerfile: Dockerfile
    volumes:
      - './services/scores:/usr/src/app'
    ports:
      - 5003:5000
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@scores-db:5432/scores_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@scores-db:5432/scores_test
      - EXERCISES_SERVICE_URL=http://exercises:5000
      - FLASK_APP=project/__init__.py
      - FLASK_ENV=development
      - SECRET_KEY=my_precious
      - USERS_SERVICE_URL=http://users:5000
    depends_on:
      - users
      - exercises
      - scores-db

  scores-db:
    build:
      context: ./services/scores/project/db
      dockerfile: Dockerfile
    ports:
      - 5438:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
